# -*- coding: utf-8 -*-
"""energy singneture 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQH8hTP1b0VktXHlfawpOH1Ea7NhY8Dz
"""

import pandas as pd
import matplotlib.pyplot as plt

#upload File
df = pd.read_csv('/content/energy_signature_old_with_ghi.csv')

# Drawing a diagram of heating and cooling energy with delta_T
plt.figure(figsize=(10, 6))

plt.scatter(df['delta_T'], df['heating_kWh'], label='Heating', alpha=0.6, color='tomato')
plt.scatter(df['delta_T'], df['cooling_kWh'], label='Cooling', alpha=0.6, color='dodgerblue')

plt.xlabel('Delta T (°C)')
plt.ylabel('Energy Consumption (kWh)')
plt.title('Energy Signature - Heating & Cooling Real Data')
plt.legend()
plt.grid(True)
plt.show()



import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# 1. Read Data
df = pd.read_csv("energy_signature_opt_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])
df["hour"] = df["time"].dt.floor("H")
df["month"] = df["time"].dt.month

# 2. Calculate the hourly average
hourly = df.groupby("hour").agg({
    "delta_T": "mean",
    "heating_kWh": "mean",
    "cooling_kWh": "mean",
    "month": "first"
}).reset_index()

# 3. Determining the season
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Other"

hourly["season"] = hourly["month"].apply(get_season)

# 4. Separating winter and summer data
winter = hourly[hourly["season"] == "Winter"]
summer = hourly[hourly["season"] == "Summer"]


#  5. Filtering outlier cooling data with a combination condition
summer = summer[~((summer["delta_T"] > -2) & (summer["cooling_kWh"] > 7))]

# 5. Winter regression training(Heating)
X_w = winter[["delta_T"]].values
y_w = winter["heating_kWh"].values
model_w = LinearRegression().fit(X_w, y_w)
y_w_pred = model_w.predict(X_w)

# 6. Summer regression training(Cooling)
X_s = summer[["delta_T"]].values
y_s = summer["cooling_kWh"].values
model_s = LinearRegression().fit(X_s, y_s)
y_s_pred = model_s.predict(X_s)

# 7. Draw a composite diagram
plt.figure(figsize=(10, 6))
plt.scatter(winter["delta_T"], y_w, color='dodgerblue', alpha=0.5, label="Winter Data (Heating)")
plt.plot(winter["delta_T"], y_w_pred, color='blue', label="Winter Regression")

plt.scatter(summer["delta_T"], y_s, color='darkorange', alpha=0.5, label="Summer Data (Cooling)")
plt.plot(summer["delta_T"], y_s_pred, color='green', label="Summer Regression")

plt.xlabel("Delta T (Indoor - Outdoor) [°C]")
plt.ylabel("Energy Consumption (kWh)")
plt.title("Hourly Energy Signature - Heating & Cooling (After Optimization)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Read Dta
df = pd.read_csv("energy_signature_old_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])
df["day"] = df["time"].dt.floor("D")
df["month"] = df["time"].dt.month

# Daily Avarage
daily = df.groupby("day").agg({
    "delta_T": "mean",
    "heating_kWh": "mean",
    "cooling_kWh": "mean",
    "month": "first"
}).reset_index()

# Detemining The Season
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Other"

daily["season"] = daily["month"].apply(get_season)

# Separating winter and summer data
winter = daily[daily["season"] == "Winter"]
summer = daily[daily["season"] == "Summer"]

# Filtering outlier cooling data with a combination condition
summer = summer[~((summer["delta_T"] > -2) & (summer["cooling_kWh"] > 7))]

# Model and Regression
X_w, y_w = winter[["delta_T"]].values, winter["heating_kWh"].values
model_w = LinearRegression().fit(X_w, y_w)
y_w_pred = model_w.predict(X_w)

X_s, y_s = summer[["delta_T"]].values, summer["cooling_kWh"].values
model_s = LinearRegression().fit(X_s, y_s)
y_s_pred = model_s.predict(X_s)

# Draw a Composite Diagram
plt.figure(figsize=(10, 6))
plt.scatter(winter["delta_T"], y_w, color='dodgerblue', alpha=0.5, label="Winter (Heating)")
plt.plot(winter["delta_T"], y_w_pred, color='blue', label="Winter Regression")

plt.scatter(summer["delta_T"], y_s, color='orange', alpha=0.5, label="Summer (Cooling)")
plt.plot(summer["delta_T"], y_s_pred, color='green', label="Summer Regression")

plt.xlabel("Delta T (Indoor - Outdoor) [°C]")
plt.ylabel("Energy Consumption (kWh)")
plt.title("Daily Energy Signature - Heating & Cooling (Befor Optimization )")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Read Data
df = pd.read_csv("energy_signature_opt_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])
df["day"] = df["time"].dt.floor("D")
df["month"] = df["time"].dt.month

# Daily Avarage
daily = df.groupby("day").agg({
    "delta_T": "mean",
    "heating_kWh": "mean",
    "cooling_kWh": "mean",
    "month": "first"
}).reset_index()

# Determining The Season
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Other"

daily["season"] = daily["month"].apply(get_season)

# Separating winter and summer data
winter = daily[daily["season"] == "Winter"]
summer = daily[daily["season"] == "Summer"]

#  Filtering outlier cooling data with a combination condition
summer = summer[~((summer["delta_T"] > -2) & (summer["cooling_kWh"] > 7))]

#  Model and Regression
X_w, y_w = winter[["delta_T"]].values, winter["heating_kWh"].values
model_w = LinearRegression().fit(X_w, y_w)
y_w_pred = model_w.predict(X_w)

X_s, y_s = summer[["delta_T"]].values, summer["cooling_kWh"].values
model_s = LinearRegression().fit(X_s, y_s)
y_s_pred = model_s.predict(X_s)

# Draw a Composite Diagram
plt.figure(figsize=(10, 6))
plt.scatter(winter["delta_T"], y_w, color='dodgerblue', alpha=0.5, label="Winter (Heating)")
plt.plot(winter["delta_T"], y_w_pred, color='blue', label="Winter Regression")

plt.scatter(summer["delta_T"], y_s, color='orange', alpha=0.5, label="Summer (Cooling)")
plt.plot(summer["delta_T"], y_s_pred, color='green', label="Summer Regression")

plt.xlabel("Delta T (Indoor - Outdoor) [°C]")
plt.ylabel("Energy Consumption (kWh)")
plt.title("Daily Energy Signature - Heating & Cooling (After Optimization)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# 1. Read Data
df = pd.read_csv("energy_signature_old_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])
df["week"] = df["time"].dt.to_period("W").apply(lambda r: r.start_time)
df["month"] = df["time"].dt.month

# 2. Weekly Avarage
weekly = df.groupby("week").agg({
    "delta_T": "mean",
    "heating_kWh": "mean",
    "cooling_kWh": "mean",
    "month": "first"
}).reset_index()

# 3. Detemaining The Season
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Other"

weekly["season"] = weekly["month"].apply(get_season)
winter = weekly[weekly["season"] == "Winter"]
summer = weekly[weekly["season"] == "Summer"]

# 4.  Model and Regression
X_w, y_w = winter[["delta_T"]].values, winter["heating_kWh"].values
model_w = LinearRegression().fit(X_w, y_w)
y_w_pred = model_w.predict(X_w)

X_s, y_s = summer[["delta_T"]].values, summer["cooling_kWh"].values
model_s = LinearRegression().fit(X_s, y_s)
y_s_pred = model_s.predict(X_s)

# 5. Draw a Composite Diagram
plt.figure(figsize=(10, 6))
plt.scatter(winter["delta_T"], y_w, color='dodgerblue', alpha=0.5, label="Winter (Heating)")
plt.plot(winter["delta_T"], y_w_pred, color='blue', label="Winter Regression")

plt.scatter(summer["delta_T"], y_s, color='orange', alpha=0.5, label="Summer (Cooling)")
plt.plot(summer["delta_T"], y_s_pred, color='green', label="Summer Regression")

plt.xlabel("Delta T (Indoor - Outdoor) [°C]")
plt.ylabel("Energy Consumption (kWh)")
plt.title("Weekly Energy Signature - Heating & Cooling (Befor Optimization)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# 1. Read Data
df = pd.read_csv("energy_signature_opt_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])
df["week"] = df["time"].dt.to_period("W").apply(lambda r: r.start_time)
df["month"] = df["time"].dt.month

# 2. Weekly Avarege
weekly = df.groupby("week").agg({
    "delta_T": "mean",
    "heating_kWh": "mean",
    "cooling_kWh": "mean",
    "month": "first"
}).reset_index()

# 3. Determining The Season
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Other"

weekly["season"] = weekly["month"].apply(get_season)
winter = weekly[weekly["season"] == "Winter"]
summer = weekly[weekly["season"] == "Summer"]

# 4.Model and Regression
X_w, y_w = winter[["delta_T"]].values, winter["heating_kWh"].values
model_w = LinearRegression().fit(X_w, y_w)
y_w_pred = model_w.predict(X_w)

X_s, y_s = summer[["delta_T"]].values, summer["cooling_kWh"].values
model_s = LinearRegression().fit(X_s, y_s)
y_s_pred = model_s.predict(X_s)

# 5. Draw a Composite Diagram
plt.figure(figsize=(10, 6))
plt.scatter(winter["delta_T"], y_w, color='dodgerblue', alpha=0.5, label="Winter (Heating)")
plt.plot(winter["delta_T"], y_w_pred, color='blue', label="Winter Regression")

plt.scatter(summer["delta_T"], y_s, color='orange', alpha=0.5, label="Summer (Cooling)")
plt.plot(summer["delta_T"], y_s_pred, color='green', label="Summer Regression")

plt.xlabel("Delta T (Indoor - Outdoor) [°C]")
plt.ylabel("Energy Consumption (kWh)")
plt.title("Weekly Energy Signature - Heating & Cooling (After Optimization)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# 1. Read Data
df = pd.read_csv("energy_signature_old_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])

# 2. Draw a Composite Diagram
plt.figure(figsize=(12, 6))

plt.plot(df["time"], df["heating_kWh"], label="District Heating", color='steelblue')
plt.plot(df["time"], df["cooling_kWh"], label="District Cooling", color='darkorange')

plt.title("District Heating and Cooling – Power Consumption Over Time")
plt.xlabel("Date")
plt.ylabel("Energy Consumption (kWh)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Read Dta
df_old = pd.read_csv("energy_signature_old_with_ghi.csv")
df_opt = pd.read_csv("energy_signature_opt_with_ghi.csv")

df_old["time"] = pd.to_datetime(df_old["time"])
df_opt["time"] = pd.to_datetime(df_opt["time"])

# Only Warm months and Active Cooling
df_old_cooling = df_old[(df_old["time"].dt.month.isin([6, 7, 8, 9])) & (df_old["cooling_kWh"] > 0)].copy()
df_opt_cooling = df_opt[(df_opt["time"].dt.month.isin([6, 7, 8, 9])) & (df_opt["cooling_kWh"] > 0)].copy()

# Applying a Conditional Filter to Cooling
mask_old = (df_old_cooling["delta_T"] > -2) & (df_old_cooling["cooling_kWh"] > 7)
mask_opt = (df_opt_cooling["delta_T"] > -2) & (df_opt_cooling["cooling_kWh"] > 7)

print("Remove Cold Weather Records:")
print(" - Befor Optimization  :", mask_old.sum())
print(" - After Optimazation :", mask_opt.sum())

df_old_cooling = df_old_cooling[~mask_old]
df_opt_cooling = df_opt_cooling[~mask_opt]

# Add a clock column for cold weather
df_old_cooling["hour"] = df_old_cooling["time"].dt.hour
df_opt_cooling["hour"] = df_opt_cooling["time"].dt.hour

# Calculation Function R²
def compute_r2_grouped(df, time_col, target_col, group_freq, feature_cols):
    df["group_time"] = df[time_col].dt.to_period(group_freq).apply(lambda r: r.start_time)
    grouped = df.groupby("group_time").agg({col: "mean" for col in feature_cols + [target_col]}).dropna()
    X = grouped[feature_cols]
    y = grouped[target_col]
    model = LinearRegression().fit(X, y)
    return r2_score(y, model.predict(X))

# Cooling: Multivariate Model
cooling_results = {}
for freq, label in zip(["H", "D", "W"], ["Hourly", "Daily", "Weekly"]):
    r2_old = compute_r2_grouped(df_old_cooling.copy(), "time", "cooling_kWh", freq, ["delta_T", "GHI", "hour"])
    r2_opt = compute_r2_grouped(df_opt_cooling.copy(), "time", "cooling_kWh", freq, ["delta_T", "GHI", "hour"])
    cooling_results[label] = (r2_old, r2_opt)

# Heating: Univariate Model
heating_results = {}
for freq, label in zip(["H", "D", "W"], ["Hourly", "Daily", "Weekly"]):
    r2_old = compute_r2_grouped(df_old.copy(), "time", "heating_kWh", freq, ["delta_T"])
    r2_opt = compute_r2_grouped(df_opt.copy(), "time", "heating_kWh", freq, ["delta_T"])
    heating_results[label] = (r2_old, r2_opt)

# Final Display of The Table
print("\n📊 R² Comparison (after removing outlier cooling data):")
print(f"{'':<10} | {'Hourly':^20} | {'Daily':^20} | {'Weekly':^20}")
print("-" * 75)
for label, results in [("Heating", heating_results), ("Cooling", cooling_results)]:
    h = results["Hourly"]
    d = results["Daily"]
    w = results["Weekly"]
    print(f"{label:<10} | {h[0]:.3f} → {h[1]:.3f}    | {d[0]:.3f} → {d[1]:.3f}    | {w[0]:.3f} → {w[1]:.3f}")



import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # for plot 3D

# Read Dta
df = pd.read_csv("energy_signature_opt_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])

# Selecting Cooling Data only in Warm months and Positive Consumption
cooling_df = df[
    (df["time"].dt.month.isin([6, 7, 8, 9])) &
    (df["cooling_kWh"] > 0)
].copy()

# Data Preparation
x = cooling_df["delta_T"]
y = cooling_df["GHI"]
z = cooling_df["cooling_kWh"]

# 3D Plot
fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111, projection='3d')

sc = ax.scatter(x, y, z, c=z, cmap='coolwarm', alpha=0.7)

ax.set_xlabel("ΔT (Indoor - Outdoor) [°C]")
ax.set_ylabel("GHI (Global Horizontal Irradiance)")
ax.set_zlabel("Cooling Energy Consumption (kWh)")
ax.set_title("3D Plot - ΔT vs GHI vs Cooling Consumption")

fig.colorbar(sc, label='Cooling (kWh)')
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.linear_model import LinearRegression

# 1. Read Data
df = pd.read_csv("energy_signature_opt_with_ghi.csv")
df["time"] = pd.to_datetime(df["time"])

# 2. Filter and Remove Cooling Data During The Summer Months
cooling_df = df[
    (df["time"].dt.month.isin([6, 7, 8, 9])) &
    (df["cooling_kWh"] > 0)
].copy()
cooling_df = cooling_df.dropna(subset=["delta_T", "GHI", "cooling_kWh"])

# 3. Data Preparation
X = cooling_df[["delta_T", "GHI"]].values
y = cooling_df["cooling_kWh"].values

# 4.Regression Model Training
model = LinearRegression().fit(X, y)

# 5. Generate a Model Sheet( surface)
x_surf, y_surf = np.meshgrid(
    np.linspace(X[:, 0].min(), X[:, 0].max(), 20),
    np.linspace(X[:, 1].min(), X[:, 1].max(), 20)
)
z_surf = model.predict(np.c_[x_surf.ravel(), y_surf.ravel()]).reshape(x_surf.shape)

# 6. Function Definition For drawing with Angles
def plot_3d(angle_elev, angle_azim, title):
    fig = plt.figure(figsize=(8, 6))
    ax = fig.add_subplot(111, projection='3d')

    # Real Point
    ax.scatter(X[:, 0], X[:, 1], y, c='red', alpha=0.5, label="Cooling Data")

    # Sheet model
    ax.plot_surface(x_surf, y_surf, z_surf, alpha=0.3, color='blue')

    # Lables
    ax.set_xlabel("ΔT (Indoor - Outdoor) [°C]")
    ax.set_ylabel("GHI (W/m²)")
    ax.set_zlabel("Cooling Energy (kWh)")
    ax.set_title(title)

    # Camera Angle
    ax.view_init(elev=angle_elev, azim=angle_azim)
    plt.tight_layout()
    plt.show()

# 7.  Draw 3D Plot
plot_3d(30, 45,"3D View – Cooling After Optimization")
plot_3d(10, 0,"Front View – GHI vs Cooling")
#plot_3d(10, 90, "Side View – ΔT vs Cooling")

!pip install tensorflow scikit-learn

import pandas as pd

# Upload Real Data
df = pd.read_csv("energy_signature_old_with_ghi.csv", parse_dates=["time"])
df = df[df["time"].dt.month.isin([11, 12, 1, 2])]  #   Just Winter

#  Extarct Feature
df["hour"] = df["time"].dt.hour
df = df[["time", "outdoor_temp", "GHI", "hour", "heating_kWh"]].dropna().set_index("time")

from sklearn.preprocessing import MinMaxScaler
import numpy as np

scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)

# DataFrame
scaled_df = pd.DataFrame(scaled, index=df.index, columns=df.columns)

def create_multivariate_sequences(data, target_col, window_size=24):
    X, y = [], []
    for i in range(len(data) - window_size):
        X.append(data.iloc[i:i+window_size].drop(columns=[target_col]).values)
        y.append(data.iloc[i+window_size][target_col])
    return np.array(X), np.array(y)

X, y = create_multivariate_sequences(scaled_df, target_col="heating_kWh", window_size=24)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

model.fit(X, y, epochs=20, batch_size=16, verbose=1)

y_pred = model.predict(X)

# Restore from Normalized scale
heating_index = list(df.columns).index("heating_kWh")
dummy = np.zeros((len(y_pred), scaled.shape[1]))
dummy[:, heating_index] = y_pred[:, 0]
y_pred_rescaled = scaler.inverse_transform(dummy)[:, heating_index]

# y واقعی
dummy_y = np.zeros((len(y), scaled.shape[1]))
dummy_y[:, heating_index] = y
y_true_rescaled = scaler.inverse_transform(dummy_y)[:, heating_index]

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print(" Multivariate LSTM Evaluation")
print("MAE:", mean_absolute_error(y_true_rescaled, y_pred_rescaled))
print("MSE:", mean_squared_error(y_true_rescaled, y_pred_rescaled))
print("R² :", r2_score(y_true_rescaled, y_pred_rescaled))

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(y_true_rescaled[:100], label="Actual", color="blue")
plt.plot(y_pred_rescaled[:100], label="Predicted", linestyle="--", color="orange")
plt.title("Multivariate LSTM Prediction of Heating_kWh-Befor Optimization")
plt.xlabel("Time Step")
plt.ylabel("Heating (kWh)")
plt.legend()
plt.grid(True)
plt.show()

#  Upload Optimaze File
df_opt = pd.read_csv("energy_signature_opt_with_ghi.csv", parse_dates=["time"])
df_opt = df_opt[df_opt["time"].dt.month.isin([11, 12, 1, 2])]

# Build a clock feature
df_opt["hour"] = df_opt["time"].dt.hour

# Just Required features
df_opt = df_opt[["time", "outdoor_temp", "GHI", "hour", "heating_kWh"]].dropna().set_index("time")

from sklearn.preprocessing import MinMaxScaler
import numpy as np

scaler_opt = MinMaxScaler()
scaled_opt = scaler_opt.fit_transform(df_opt)

scaled_df_opt = pd.DataFrame(scaled_opt, index=df_opt.index, columns=df_opt.columns)

def create_multivariate_sequences(data, target_col, window_size=24):
    X, y = [], []
    for i in range(len(data) - window_size):
        X.append(data.iloc[i:i+window_size].drop(columns=[target_col]).values)
        y.append(data.iloc[i+window_size][target_col])
    return np.array(X), np.array(y)

X_opt, y_opt = create_multivariate_sequences(scaled_df_opt, target_col="heating_kWh", window_size=24)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

model_opt = Sequential()
model_opt.add(LSTM(64, activation='relu', input_shape=(X_opt.shape[1], X_opt.shape[2])))
model_opt.add(Dense(1))
model_opt.compile(optimizer='adam', loss='mse')

model_opt.fit(X_opt, y_opt, epochs=20, batch_size=16, verbose=1)

y_pred_opt = model_opt.predict(X_opt)

# Restore from Normalized scale
heating_index = list(df_opt.columns).index("heating_kWh")
dummy_opt = np.zeros((len(y_pred_opt), scaled_opt.shape[1]))
dummy_opt[:, heating_index] = y_pred_opt[:, 0]
y_pred_opt_rescaled = scaler_opt.inverse_transform(dummy_opt)[:, heating_index]

#  Real Y
dummy_y_opt = np.zeros((len(y_opt), scaled_opt.shape[1]))
dummy_y_opt[:, heating_index] = y_opt
y_true_opt_rescaled = scaler_opt.inverse_transform(dummy_y_opt)[:, heating_index]

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print(" Multivariate LSTM Evaluation - OPT")
print("MAE:", mean_absolute_error(y_true_opt_rescaled, y_pred_opt_rescaled))
print("MSE:", mean_squared_error(y_true_opt_rescaled, y_pred_opt_rescaled))
print("R² :", r2_score(y_true_opt_rescaled, y_pred_opt_rescaled))

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(y_true_opt_rescaled[:100], label="OPT Actual", color="green")
plt.plot(y_pred_opt_rescaled[:100], label="OPT Predicted", linestyle="--", color="orange")
plt.title("Multivariate LSTM Prediction of Heating_kWh (Optimized)")
plt.xlabel("Time Step")
plt.ylabel("Heating (kWh)")
plt.legend()
plt.grid(True)
plt.show()